import { CartPositionProp } from '@/widgets/cart-position/CartPosition.type'

export const cartPositions: CartPositionProp[] = [
  {
    id: '1',
    amount: 3,
    image: '/pizza.webp',
    price: '5,99',
    title: 'American Favorite',
    maxAvailable: 13,
    onDecrement: () => {},
    onIncrement: () => {},
    onEdit: () => {},
  },
  {
    id: '2',
    amount: 1,
    image: '/pizza.webp',
    price: '7,59',
    title: 'Mushroom Dream',
    maxAvailable: 7,
    onDecrement: () => {},
    onIncrement: () => {},
    onEdit: () => {},
  },
  {
    id: '3',
    amount: 2,
    image: '/pizza.webp',
    price: '6,29',
    title: 'Super Cheesee',
    maxAvailable: 9,
    onDecrement: () => {},
    onIncrement: () => {},
    onEdit: () => {},
  },
  {
    id: '1',
    amount: 3,
    image: '/pizza.webp',
    price: '5,99',
    title: 'American Favorite',
    maxAvailable: 13,
    onDecrement: () => {},
    onIncrement: () => {},
    onEdit: () => {},
  },
  {
    id: '2',
    amount: 1,
    image: '/pizza.webp',
    price: '7,59',
    title: 'Mushroom Dream',
    maxAvailable: 7,
    onDecrement: () => {},
    onIncrement: () => {},
    onEdit: () => {},
  },
  {
    id: '3',
    amount: 2,
    image: '/pizza.webp',
    price: '6,29',
    title: 'Super Cheesee',
    maxAvailable: 9,
    onDecrement: () => {},
    onIncrement: () => {},
    onEdit: () => {},
  },
]
